import { type NextPage } from 'next';

import Head from 'next/head';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen flex-col items-center justify-center bg-dawn">
                <header></header>

                <h1 className="font-medium text-9xl">Music unites</h1>
                <body></body>
            </main>
        </>
    );
};

export default Home;
