import type { NextPage } from "next";
import Head from "next/head";
import { Menu } from "./components/menu";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>bookr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu/>
    </div>
  );
};

export default Home;
